INSERT INTO black (text, pack, pick, draw) VALUES (E'Before we start, my safeword is ______.', E'BDSM Pack (CC:G5W7T)', 1, 1);
INSERT INTO black (text, pack, pick, draw) VALUES (E'I was scandalized when my partner told me they were into ______.', E'BDSM Pack (CC:G5W7T)', 1, 1);
INSERT INTO black (text, pack, pick, draw) VALUES (E'My friends discovered I\'m into ______ and they won\'t stop kinkshaming me.', E'BDSM Pack (CC:G5W7T)', 1, 1);
INSERT INTO black (text, pack, pick, draw) VALUES (E'Daddy\'s ______ are great.', E'BDSM Pack (CC:G5W7T)', 1, 1);
INSERT INTO black (text, pack, pick, draw) VALUES (E'When my Master blindfolds me, I can only think about ______.', E'BDSM Pack (CC:G5W7T)', 1, 1);
INSERT INTO black (text, pack, pick, draw) VALUES (E'______, the one thing I can\'t admit I like.', E'BDSM Pack (CC:G5W7T)', 1, 1);
INSERT INTO black (text, pack, pick, draw) VALUES (E'I think Susan is into ______.', E'BDSM Pack (CC:G5W7T)', 1, 1);
INSERT INTO black (text, pack, pick, draw) VALUES (E'I can\'t understand why people are into ______.', E'BDSM Pack (CC:G5W7T)', 1, 1);
INSERT INTO black (text, pack, pick, draw) VALUES (E'In the last scene I had with my partner, they did ______ with me.', E'BDSM Pack (CC:G5W7T)', 1, 1);