INSERT INTO white (text, pack) VALUES (E'literally any kink', E'BDSM Pack (CC:G5W7T)');
INSERT INTO white (text, pack) VALUES (E'cummies', E'BDSM Pack (CC:G5W7T)');
INSERT INTO white (text, pack) VALUES (E'rope that burns too much and handcuffs too tight', E'BDSM Pack (CC:G5W7T)');
INSERT INTO white (text, pack) VALUES (E'weird bondage futanari manga', E'BDSM Pack (CC:G5W7T)');
INSERT INTO white (text, pack) VALUES (E'daddy kink', E'BDSM Pack (CC:G5W7T)');
INSERT INTO white (text, pack) VALUES (E'Omorashi kink', E'BDSM Pack (CC:G5W7T)');
INSERT INTO white (text, pack) VALUES (E'daddy issues', E'BDSM Pack (CC:G5W7T)');
INSERT INTO white (text, pack) VALUES (E'being kinkshamed', E'BDSM Pack (CC:G5W7T)');
INSERT INTO white (text, pack) VALUES (E'being tied up and losing the key', E'BDSM Pack (CC:G5W7T)');