INSERT INTO white (text, pack) VALUES (E'🍆💦💦💦', E'Emoji Pack (CC:89VN4)');
INSERT INTO white (text, pack) VALUES (E'🍑👈🍆?', E'Emoji Pack (CC:89VN4)');
INSERT INTO white (text, pack) VALUES (E'🤷', E'Emoji Pack (CC:89VN4)');
INSERT INTO white (text, pack) VALUES (E'Singing \'Rock Around The Clock\' but in emojis 1️⃣,2️⃣,🕒,🕓,🎸❗ 5️⃣,6️⃣,🕖,🕗,🎸❗ 9️⃣,🔟,🕚,🕛,🎸❗', E'Emoji Pack (CC:89VN4)');
INSERT INTO white (text, pack) VALUES (E'......... "💍👰?" ........ "🤔🤔🤔...🙅⛔ 💖😍🧑🏿🏋🏿🍆💖" "💔😧😭😴💤🌖 ☀️😑😱😭🔫❗💀"', E'Emoji Pack (CC:89VN4)');